### ISSUE TITLE
dlsite play: Comic Viewer support

### ISSUE THREAD

**Issue by randomTL** [bhrevol/dlsite-async#161]
is comic viewer product supported (sample: https://www.dlsite.com/books/work/=/product_id/BJ01648640.html?locale=en_US)? getting KeyError: 'optimized'

**Comment by bhrevol** [comment]
Comic viewer is not supported (for files that show up as `ebook_full` in playfile listing)

I should open a separate issue for this, but the `https://play.dlsite.com/csr/viewer/hybrid?...` diazepam viewer that is used for some newer dedicated viewer (.dlst) books is also not supported.

In both cases dlsite play does not load the page images through the playfile/ziptree system, and I haven't reverse engineered any of the newer viewers.

**Comment by bhrevol** [comment]
Downloading comic viewer works is now supported in v0.6.0 which was just released. You will need to use the new `EbookSession` for these works, see the updated readme for examples.
