### ISSUE TITLE
Webtoon

### ISSUE THREAD

**Issue by randomTL** [bhrevol/dlsite-async#167]
is webtoon will be supported? (type: ebook_webtoon)
sample: https://www.dlsite.com/books/work/=/product_id/BJ01785778.html

**Comment by bhrevol** [comment]
Webtoons use the same format as comic viewer ebooks, I released `0.6.1` with support for downloading the images for webtoons.

At some point I'll parse the page layout info and add support for stitching the vertical webtoon images together, but don't have time to get into it right now. In the meantime this should still be straightforward for the user to handle themselves with [Pillow](https://pillow.readthedocs.io/en/stable/handbook/tutorial.html#cutting-pasting-and-merging-images) just based on the `{pagenumber}-{slice}.webp` filenaming scheme for webtoons.
